### ISSUE TITLE
Display user friendly error messages when data is not being brought over.  (Server side message - needs info from QEWD)

### ISSUE THREAD

**Issue by juliashulga** [PulseTile/PulseTile-React-Core#162] opened 2018-06-05 09:07 UTC
![img_05062018_090930_0](https://user-images.githubusercontent.com/39296691/40966356-f6d58b06-68b8-11e8-98da-324080255f7b.png)

**Comment by kuvakina** [comment] 2018-07-07 19:02
We couldn't repeat the error, but added messages:

- connection error: 'Some connection error has occurred. Please check your connection and try again.'
- 403 or 400 with token's problems: 'Your session has expired. Click the button to log in again'
- 400: 'Error 400: { text of error }'
- 404: 'API is currently unavailable'
- server errors: 'Something is wrong with the server. Please try again later.'
- by default: 'Something wrong'

@tony-shannon Can we consider this task Done?

**Comment by tony-shannon** [comment] 2018-07-10 12:30
thanks @kuvakina 
this probably needs a bit of discussion with @robtweed if he can provide QEWD side message if a service eg openEHR/other is down and not retrieving data
The pic above shows Allergies, Meds etc without data..but without explaining why they were empty
So thanks for the progress made but lets connect with Rob on this one
thanks
Tony

**Comment by kuvakina** [comment] 2018-07-10 13:46
@tony-shannon Ok, I understand, thank you.

**Comment by tony-shannon** [comment] 2018-08-14 13:10
Hi @Robtweed
can you please comment on other messages that you could pass to the UI ?
eg agree an error message type that PulseTile handle and you can then decide on the content 
eg "EtherCIS down" etc

**Comment by tony-shannon** [comment] 2018-09-28 15:19
this needs to remain open

**Comment by simongamester** [comment] 2018-10-03 13:31
Need to consider a standardised method of returning error messages from the api. In the event that an error occurs i.e. not a 200 response, an error object could be returned containing an error code, a simple description of the error and possibly a technical description. Example from twitter api here - https://developer.twitter.com/en/docs/ads/general/guides/response-codes

May also need to consider a list of known error codes so PulseTile could interpret them correctly.

**Comment by BogdanScherban** [comment] 2018-10-03 13:49
I need to talk with Rob - how to reproduce any server error (code > 499) at my local-machine.

**Comment by PhilBarrett** [comment] 2018-10-08 13:29
Revisit notifications work and Toaster messages (bootstrap)
![IMG_08102018_142542_0.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a6886ed18902a00110228a6/125516c66e82c728ace21e0d46c1b9bd1cd2dbf8dfbbef12fc62a1c07b1373211654e1673295f127b54778154d555ca913090c11fffcdf2cf4e56d75de5c0be4d2385677936b14bea4905dee5fee7fd616cfe3fe9846d2e93b2fe68e8c463e1e001b8ef95936a88b06.png)

**Comment by BogdanScherban** [comment] 2018-10-09 10:18
We have two questions about this issue:

1) We can't have more than one request about error. Let's look on info about error requests in our Storage: 
![requestError.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bb3796441a5980011efd33d/125516c66e82c728ace21e0d46fa918b368790bdaafbad4cb61fbcd6395428792c07b7692ac7b62abe417e525a0949fe12095a10fcf98028f3bf3f25dc5919f1c32f0e2a92624cf5f2d75dad0ba821824584b3bf834cc8e83d24e48d8f462c53.png)

so, should we show the notifications number if can't be more than 1?

2) Toaster is good if we want only to show text of error message. But it isn't interactive. We can't add the button 'Reload page', 'Cancel' or 'OK' to the Toaster.

**Comment by tony-shannon** [comment] 2018-10-09 12:00
have asked @BogdanScherban and Alena to look at this library
http://igorprado.com/react-notification-system/

**Comment by tony-shannon** [comment] 2018-10-09 12:28
Lets lay out some of the key requirements here
A means to notify users - for information, errors etc
A means for users to take action -eg via button

Some messages will be for information only, not for action
Some messages will be for information and action

**Comment by BogdanScherban** [comment] 2018-10-09 12:42
@tony-shannon 

I've read attentively description of this library. It can be used for both scenarios (A & B).

But I see one problem for B.
It doesn't give possibility to prevent any user's action until user click on toaster block button.

**Comment by tony-shannon** [comment] 2018-10-09 12:46
> But I see one problem for B.
> It doesn't give possibility to prevent any user's action until user click on toaster block button.

So you are saying it cant replace modals? Can you give scenario from our current use of modals please?

**Comment by PhilBarrett** [comment] 2018-10-09 12:59
http://igorprado.com/react-notification-system/ just checked it out and it looks really neat. As we're not really using modals anymore this could be more appropriate, plus auto dismiss functions etc, it has a lot of possibilities. 

e.g. 
When new features are released (could it launch a new tab when you click on the Action Button
Positive response to an action taken by the user, saved/submitted/updated
User errors (but personally i think in line errors are better)
When systems are down or connectivity is poor
Notifying of downtime

I've seen from the PR's there are some accessibility enhancements that would be helpful for screenreaders etc but certainly something we could explore in a dev environment and if suitable, pursue in a future release

**Comment by BogdanScherban** [comment] 2018-10-09 12:59
@tony-shannon 

_"Can you give scenario from our current use of modals please?"_
Right now Core uses following scenario:
1) App is loading...
2) We check is request error presented;
3) Is error is presented we check its code;
4) Depends on error code we output **modal window** with some message and interactive buttons.

_"So you are saying it cant replace modals?"_
Yes, because we have three types of error, when user must reload page or be redirect to the root page:
1) if session has expired (redirect to the root);
2) if some connection error has occurred (reload page);
3) in case server error (reload page).

If we will use Toaster in these three cases user would continue work without reloading/redirecting/relogining etc.

**Comment by tony-shannon** [comment] 2018-10-09 13:19
@BogdanScherban  
See the custom button functionality within the library
So this can trigger page reload or redirect
![image](https://user-images.githubusercontent.com/939996/46671994-394f4d00-cbce-11e8-91ac-28d2e995e796.png)

Please explore this and report back
https://github.com/igorprado/react-notification-system#action

**Comment by BogdanScherban** [comment] 2018-10-10 10:03
@tony-shannon 

Tony, we discussed this issue with @kbeloborodko and have the following suggestions:

1) We can use toastr-library for error messages, that don't require user interactivity. There are three types of messages (type A):
- error 400;
- error 404 (API is unavailable);
- default message for undefined errors (like 'Something is wrong').
In these cases it isn't necessary to block the browser window, and we can use Toaster for these errors.

2) But if we will use Toastr-library for type A errors, we will have two errors handlers (modal and toaster) instead of one (modal). And this functionality will need in test coverage. Is it convenient?

**Comment by simongamester** [comment] 2018-10-11 12:03
Just wanted to provide some feedback on this thread.

1. I'm not sure the Toasty-library (https://codeseven.github.io/toastr/) is the right choice. It appears to require jQuery, so not keen to add this as well. Suggest we use http://igorprado.com/react-notification-system/ instead.

2. I think we should continue to use existing modals for errors which force interaction from the user, such as a login timeout which requires a page reload. 

3. Instances where there there is a lot of information within the modal i.e. terms and conditions. We don't have any examples of this in the current Helm version, but other PulseTile plugins include these types of modals.

3. React notifications should be used in all other cases i.e. connectivity issues with the api. Confirmations that something has been changed, removed or added etc.

Simon

**Comment by tony-shannon** [comment] 2018-10-12 11:45
I'm going to close this issue for the moment, as on discussion with @robtweed we are probably passing as much error info as we need to from qewd to pulsetile,
Can be reopened if needs be in future

**Closed by tony-shannon** 2018-10-12 11:45 UTC
Labels: Medium Priority, PulseTile, QEWD, to do

**Comment by PhilBarrett** [comment] 2018-10-16 10:12
Discussed with Rob. Enough information is being passed, can be closed for now
